name: Build new CV Version
on:
  push:
    branche: ci
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      #- name: Package Latest Version as a Release
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: latest
      #    path: "*-cv-adam.pdf"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*-cv-adam.pdf"
          body: "TODO release body"
